### ISSUE TITLE
Dyes

### ISSUE THREAD

**Issue by Villfuk02** [bigyihsuan/complicated-recipes-2#5]
Your dye crafting makes no sense, because everything is from wood. I suggest making dyes like this:
(also wood is very bad resource to utilize in higher tech)

Green - wood
Black - coal
Yellow - also wood

red - iron + water (rust)
blue - copper + sulfuric acid (cupric sulfate)
?more orange/yellow - sulfur
?tons of green - uranium-235
?more orange - uranium-238 (uranium oxide)

and of course combining colors is fine (red + yellow = orange)

**Comment by bigyihsuan** [comment]
I'll take a look at it. I'm working on it right now, but I'm having trouble finding suitable recipes because most of the materials in real life don't exist in-game from vanilla, except for Bob's.

Currently, they're mixing ores or other materials with water or sulfuric acid to yield 100 of each.
